apiVersion: v1
kind: Pod
metadata:
  name: pod=pv
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      volumeMounts:
        - mountPath: /volume-dentro-container
          name: primeiro-pv
      ports:
        - containerPort: 80
  volumes:
    - name: primeiro-volume
      persistentVolumeClaim:
        claimName: pvc-1
